# Generated by Django 5.2.16 on 2026-07-26 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_auditoria_corpus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContextoNormativoC0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrutura_diploma', models.JSONField(blank=True, default=dict)),
                ('conceitos_centrais', models.JSONField(blank=True, default=list)),
                ('territorios', models.JSONField(blank=True, default=list)),
                ('remissoes_cruzadas', models.JSONField(blank=True, default=list)),
                ('temas_cobertos', models.JSONField(blank=True, default=list)),
                ('cobertura_integral', models.BooleanField(default=False)),
                ('gerado_por_modelo', models.CharField(blank=True, max_length=120)),
                ('versao_prompt', models.CharField(blank=True, max_length=40)),
                ('revisado', models.BooleanField(default=False)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aplicacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contexto_c0', to='applications.aplicacaomunicipal')),
                ('release_corpus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contextos_c0', to='applications.releasecorpus')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contextos_normativos_c0_revisados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contexto normativo C0',
                'verbose_name_plural': 'contextos normativos C0',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LivroCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_artigos', models.PositiveIntegerField(default=0)),
                ('total_lidos', models.PositiveIntegerField(default=0)),
                ('total_revisados', models.PositiveIntegerField(default=0)),
                ('cobertura_percentual', models.FloatField(default=0.0)),
                ('lacunas', models.JSONField(blank=True, default=list)),
                ('alertas', models.JSONField(blank=True, default=list)),
                ('gerado_em', models.DateTimeField(blank=True, null=True)),
                ('sha256_estado', models.CharField(blank=True, max_length=64)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('release_corpus', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='livro_cobertura', to='applications.releasecorpus')),
            ],
            options={
                'verbose_name': 'livro de cobertura',
                'verbose_name_plural': 'livros de cobertura',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LeituraIntegral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumo', models.TextField(blank=True)),
                ('conceitos_identificados', models.JSONField(blank=True, default=list)),
                ('territorios_mencionados', models.JSONField(blank=True, default=list)),
                ('remissoes', models.JSONField(blank=True, default=list)),
                ('cobertura_tematica', models.JSONField(blank=True, default=list)),
                ('lido_por_modelo', models.CharField(blank=True, max_length=120)),
                ('versao_prompt', models.CharField(blank=True, max_length=40)),
                ('confianca', models.FloatField(blank=True, null=True)),
                ('revisado', models.BooleanField(default=False)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aplicacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras_integrais', to='applications.aplicacaomunicipal')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras', to='applications.artigonormativo')),
                ('release_corpus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras_integrais', to='applications.releasecorpus')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras_integrais_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'leitura integral',
                'verbose_name_plural': 'leituras integrais',
                'ordering': ['aplicacao', 'artigo'],
                'unique_together': {('aplicacao', 'artigo', 'release_corpus')},
            },
        ),
    ]
