from django.urls import path

from .views import (
    baixar_artefato,
    detalhe_aplicacao,
    detalhe_artefato,
    detalhe_artigo,
    detalhe_ato,
    detalhe_documento,
    detalhe_ocorrencia,
    detalhe_pagina,
    detalhe_processamento,
    detalhe_release,
    exibir_pdf,
    inicio,
    leitor_documento,
    lista_aplicacoes,
    lista_artigos,
    lista_atos,
    lista_ocorrencias,
    lista_releases,
)

urlpatterns = [
    path("", inicio, name="inicio"),
    path("aplicacoes/", lista_aplicacoes, name="lista_aplicacoes"),
    path("aplicacoes/<int:pk>/", detalhe_aplicacao, name="detalhe_aplicacao"),
    path("atos/", lista_atos, name="lista_atos"),
    path("atos/<int:pk>/", detalhe_ato, name="detalhe_ato"),
    path("artigos/", lista_artigos, name="lista_artigos"),
    path("artigos/<int:pk>/", detalhe_artigo, name="detalhe_artigo"),
    path("documentos/<int:pk>/", detalhe_documento, name="detalhe_documento"),
    path("documentos/<int:pk>/leitor/", leitor_documento, name="leitor_documento"),
    path("ocorrencias/", lista_ocorrencias, name="lista_ocorrencias"),
    path("ocorrencias/<int:pk>/", detalhe_ocorrencia, name="detalhe_ocorrencia"),
    path("releases/", lista_releases, name="lista_releases"),
    path("releases/<int:pk>/", detalhe_release, name="detalhe_release"),
    path("versoes/<int:pk>/pdf/", exibir_pdf, name="exibir_pdf"),
    path("processamentos/<int:pk>/", detalhe_processamento, name="detalhe_processamento"),
    path("paginas/<int:pk>/", detalhe_pagina, name="detalhe_pagina"),
    path("artefatos/<int:pk>/", detalhe_artefato, name="detalhe_artefato"),
    path("artefatos/<int:pk>/baixar/", baixar_artefato, name="baixar_artefato"),
]
